import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SignIn from "@/components/authComp/signInButton";
import { SessionProvider } from "next-auth/react";
import Navbar from "../components/Navbar"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const playFair = localFont({
  src: "./fonts/PlayfairDisplay-Regular.ttf",
  variable: "--font-playfair-display",
  weight: "400 400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider >
        <body
          className={`${playFair.variable} ${playFair.variable} antialiased`}
        >
          <Navbar/>
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
